### ISSUE TITLE
boost::this_thread::hidden::sleep_until(timespec const&)’未定义的引用

### ISSUE THREAD

**Issue by nuo-code** [lianghongzhuo/pygpg#1]
Hello, I encountered an error when using your library，libgrasp_candidates_generator.so：对‘boost::this_thread::hidden::sleep_until(timespec const&)’未定义的引用，My boost library version is 1.65.1，Can you give me some help？Thank you

**Comment by lianghongzhuo** [comment]
Hello, I need more information to figure out your issues. How did you use this package? So that I can try to reproduce your issues.

**Comment by nuo-code** [comment]
Thank you very much for your reply. I have solved this problem. Could you please tell me how to use your library？

**Comment by lianghongzhuo** [comment]
the demo is updated.
